# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'HopeIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for HopeIt
    pod 'BraintreeDropIn'
    pod 'Braintree/PayPal'
    pod 'Braintree/Venmo'
    pod 'Braintree/Apple-Pay'
    pod 'Braintree/3D-Secure'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            
            # Configure Pod targets for Xcode 8 compatibility
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
