project 'HopeIt.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HopeIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HopeIt
	pod 'BraintreeDropIn'
	pod 'Braintree/PayPal'
	pod 'Braintree/Venmo'
	pod 'Braintree/Apple-Pay'
	pod 'Braintree/3D-Secure'
end
